spring.application.name=study-companion

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_study_companion
spring.datasource.username=study_app
spring.datasource.password=StudyApp@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=9192

# File Upload
app.upload.dir=uploads

# Multipart Upload Limits
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB